services:
  - type: web
    name: discord-bot
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python Bot.py
    plan: free
    region: frankfurt
    branch: main
    healthCheckPath: /
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        value: "1397164536204759090"
      - key: PORT
        value: "10000"
      - key: TIMEZONE
        value: "UTC"
